# Generated by Django 4.2.2 on 2024-01-09 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(auto_now_add=True, verbose_name='datea')),
                ('title', models.CharField(max_length=255, verbose_name='application_title')),
                ('details', models.TextField(verbose_name='application_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'ordering': ['datea'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='kind_title')),
            ],
            options={
                'db_table': 'kind',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='manufacturer_title')),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='replica_title')),
                ('capacity', models.CharField(max_length=128, verbose_name='capacity')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replica_kind', to='shipping.kind')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replica_manufacturer', to='shipping.manufacturer')),
            ],
            options={
                'db_table': 'replica',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='driver_full_na_07a886_idx')],
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.IntegerField(verbose_name='yr')),
                ('reg_number', models.CharField(max_length=64, unique=True, verbose_name='reg_number')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobile_driver', to='shipping.driver')),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobile_replica', to='shipping.replica')),
            ],
            options={
                'db_table': 'automobile',
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datew', models.DateTimeField(verbose_name='datew')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('finish', models.DateTimeField(verbose_name='finish')),
                ('whence', models.CharField(max_length=255, verbose_name='whence')),
                ('where', models.CharField(max_length=255, verbose_name='where')),
                ('details', models.TextField(verbose_name='waybill_details')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_automobile', to='shipping.automobile')),
            ],
            options={
                'db_table': 'waybill',
                'ordering': ['datew'],
                'indexes': [models.Index(fields=['datew'], name='waybill_datew_b99b52_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(verbose_name='datem')),
                ('status', models.CharField(max_length=128, verbose_name='movement_status')),
                ('details', models.TextField(blank=True, null=True, verbose_name='movement_details')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_application', to='shipping.application')),
            ],
            options={
                'db_table': 'movement',
                'ordering': ['datem'],
                'indexes': [models.Index(fields=['application'], name='movement_applica_27871b_idx'), models.Index(fields=['datem'], name='movement_datem_8708fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['datea'], name='application_datea_198fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_ba75f5_idx'),
        ),
    ]
